[forest]
trees = [
    "trees/general",
    "trees/utils",
    "trees/localcharts-files",
    "trees/people",
    "trees/refs",
    "trees/old-blog-files",
    "trees/public-trees",
]
assets = ["assets"]
home = "index"
url = "https://erischel.com"
